# Generated by Django 2.1.2 on 2018-12-01 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_auto_20181130_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.UUIDField(default=uuid.UUID('cf6442e9-b23e-4f76-a1ed-17f8a4ff744b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.UUIDField(default=uuid.UUID('f8f292ca-cfaa-4e43-bf3d-7dcc9713bf1e'), primary_key=True, serialize=False),
        ),
    ]
